/* Presenter walkthrough steps — shared by the demo page (for navigation/spotlight)
   and the separate Presenter Notes window (for the private script).
   Each step: section + sel (where to navigate/highlight on the demo) and the
   coaching notes (manual / problem / ai / say / click / watch). */
window.PRESENT_STEPS = [
  { section: "overview", sel: ".run-demo-bar",
    title: "Open — frame it before you click anything",
    what: "The whole pitch in one sentence. Say this FIRST, with the room's editors in mind.",
    say: "Before I show anything: this makes your editors faster and keeps them in control — it does not replace them. A lot of their day is manual, repetitive work. For each part I'll show what it costs you by hand, then what the system does instead. Nothing publishes without an editor.",
    click: "Don't click yet. Say the line, pause, then begin.",
    watch: "The most important sentence of the meeting. Say it slowly, looking at the writers, not just the bosses." },

  { section: "overview", sel: "#stat-grid",
    title: "1 · We studied YOUR real content",
    what: "Live statistics from Qatar Living's own corpus — the credibility foundation.",
    say: "We studied 1,999 of your own articles and 118 events. These numbers come from your pages — not generic AI claims.",
    click: "Point across the stat cards — quotes per article, stale events, headline sameness.",
    watch: "Lead with their content, not AI features. This earns the right to show AI to skeptics." },

  { section: "evidence", sel: "#section-evidence .section-head",
    title: "2 · The diagnosis — where the manual hours go",
    manual: "Today your team hand-writes every story, hand-crafts every headline, tags by hand, and tidies copy before publishing.",
    problem: "It shows in the corpus: 0.79 quotes per article (65% have none) — mostly repackaged wire copy; 97.3% of headlines the same proper-noun shape; everything tagged just 'News'; 57.6% of events already ended.",
    ai: "Every one of those is work the pilot can take off their plate. The next screens show each, one at a time.",
    say: "Here's the pattern in your own content: a lot of skilled-editor time goes into mechanical work — repackaging, formatting, tagging, cleanup — leaving too little for real reporting.",
    click: "Scroll the evidence: headline openers, stance verbs, avoidance terms.",
    watch: "Frame it as 'your team is mis-deployed' — never 'too many people'." },

  { section: "radar", sel: ".radar-bar",
    title: "3 · Live News Radar",
    manual: "Editors watch QNA, The Peninsula and Gulf Times all day, by hand, to spot what to cover.",
    problem: "It's slow and reactive, stories slip through, and there's no consistent read on what's sensitive.",
    ai: "The pilot watches all those sources continuously, risk-classifies each item, and refreshes on its own.",
    say: "Today someone keeps tabs on all these sources by hand. This watches them for you — live, around the clock.",
    click: "Point at the live items and the 'last updated' time. Let 'live' land.",
    watch: "Say 'live' clearly — make sure they register it's not a slideshow." },

  { section: "radar", sel: "#radar-auto",
    title: "4 · Auto-prepare → the queue",
    manual: "For each story an editor reads the source and re-types it into Qatar Living format from scratch.",
    problem: "Minutes per story, voice varies by who's writing, and it's transcription more than reporting.",
    ai: "One click drafts the top stories in your tone straight into the approval queue.",
    say: "Instead of retyping every story by hand, the desk wakes up to drafts already prepared — prepared, not published. An editor still approves each one.",
    click: "Click 'Auto-prepare top 3' (or 'Prepare in QL style' on one item).",
    watch: "Every time you say 'prepared', say 'an editor approves'." },

  { section: "compare", sel: "#section-compare .section-head",
    title: "5 · Compare to Real ★ (the honesty screen)",
    manual: "An editor writes the article from scratch; quality and consistency vary by who's on shift.",
    problem: "It's subjective and slow, with no objective check against house style.",
    ai: "From the same facts, the pilot drafts a source-faithful version in your voice — and you judge it.",
    say: "Left is your actual published article. Right is ours from the same facts. The score is adherence to your style rules — not whether ours is 'better than Qatar Living'. You decide.",
    click: "Open one sample (aviation works well) and let them read both columns.",
    watch: "Do NOT claim it beats them. Being honest here wins the room." },

  { section: "paraphrase", sel: "#section-paraphrase .section-head",
    title: "6 · Paraphrase any source",
    manual: "Editors read a wire story and re-report it by hand — often ending up near-copying it.",
    problem: "It's slow transcription, and copying hurts originality and SEO.",
    ai: "It re-reports the story in fresh wording — facts and quotes preserved — with a faithfulness check so it can't clone the source.",
    say: "Paste any outlet's story. Instead of retyping it, you get an original re-report in your tone, with the facts intact.",
    click: "Paste a wire story, run it, show the copy buttons.",
    watch: "Say 'reworded, not copied' — it actively checks overlap." },

  { section: "generate", sel: "#section-generate .section-head",
    title: "7 · Generate all formats + catch it failing",
    manual: "Editors write the article, then separately craft the social post, the push and the story for each channel.",
    problem: "Repackaging across channels eats hours — and the real worry with AI is that it might make things up.",
    ai: "One brief → article + Instagram + push + story; and the grounding check flags anything not in the source.",
    say: "From one brief: all your formats. And watch — I'll feed it a 'fact' that isn't in the brief… see, it flags it in red. It tells you when it's unsure. It doesn't pretend.",
    click: "Generate normally first. Then add an unsupported 'fact' and show the grounding flag.",
    watch: "This live catch converts AI skeptics more than any feature." },

  { section: "checker", sel: "#section-checker .section-head",
    title: "8 · Style Checker (honestly named)",
    manual: "Consistency relies on each editor remembering house style; a senior editor re-checks by hand.",
    problem: "Honorifics and voice drift, and the senior reviewer becomes a bottleneck.",
    ai: "An objective 0–100 score for adherence to YOUR extracted rules, in seconds.",
    say: "This measures adherence to your rules — we renamed it from 'quality' on purpose, because you were right that 'quality' overclaimed.",
    click: "Paste text and show the 7-dimension breakdown.",
    watch: "Honest naming answers Anis's number-one past objection — call it out." },

  { section: "governance", sel: "#section-governance .section-head",
    title: "9 · Governance gate (control = trust)",
    manual: "Editors judge by gut what's sensitive — royals, ministries, security — and route it informally.",
    problem: "It's inconsistent, and a sensitive item can slip straight through to publish.",
    ai: "Every item is auto risk-tiered, routed to the right reviewer, and marked no-auto-publish.",
    say: "Anything touching royals, ministries, diplomacy or security is routed to senior plus legal review automatically. Control is built in, not bolted on.",
    click: "Click the Sensitive-News one-click demo; show the high-risk routing.",
    watch: "Lead with control for skeptics — this screen says 'you're safe'." },

  { section: "freshness", sel: "#freshness-summary",
    title: "10 · Event freshness (an easy yes)",
    manual: "Someone would have to manually check 100+ events' dates to catch the expired ones.",
    problem: "Nobody has time, so 57.6% of your listed events already ended — and 0 were ever marked cancelled.",
    ai: "The pilot auto-flags every stale event with a suggested fix for approval.",
    say: "Today nobody checks these by hand, so more than half your live events already ended. This flags each one with a fix.",
    click: "Show the stale list and a suggested action.",
    watch: "Low-trust, high-drudgery win — the easy 'yes' to start a pilot on." },

  { section: "cleanup", sel: "#section-cleanup .section-head",
    title: "11 · CMS Cleanup (the foot in the door)",
    manual: "Before publishing, editors hand-clean paste artefacts and stamp the same sign-off boilerplate.",
    problem: "It's tedious and inconsistent — the identical CTA paragraph ended up in ~1,425 articles.",
    ai: "One click removes the repeated boilerplate and paste artefacts and normalizes the markup.",
    say: "The boring pre-publish tidy-up — the repeated boilerplate, the paste junk — done in a click. No creativity, no trust required.",
    click: "Paste a sample body, run cleanup, show the before/after counts.",
    watch: "Lead with the repeated BOILERPLATE (it's visible on the page). Do NOT headline 'nbsp' — it renders fine for readers; it's a markup/SEO point, not a visible bug." },

  { section: "copilot", sel: "#section-copilot .section-head",
    title: "12 · Editorial Copilot (your editors train it)",
    manual: "Approvals and edits happen in people's heads and email — no record, no learning.",
    problem: "The system never improves systematically, and there's no audit trail.",
    ai: "A review queue — approve / edit / reject-with-reason — and those reasons train the prompts over time.",
    say: "Every edit your editors make trains it. They become the editors-in-chief of an assistant that learns your house style. Acceptance rate is the KPI.",
    click: "Approve one, edit one, reject one with a reason; show the learning panel.",
    watch: "Answers both 'how does it improve?' and the job-fear. Linger here." },

  { section: "cms", sel: "#section-cms .section-head",
    title: "13 · CMS Integration (an honest mock)",
    manual: "Editors copy-paste between the writing tool and the CMS.",
    problem: "Friction, and a place for errors to creep in.",
    ai: "Read-only pull of opportunities, draft-only push — a human always publishes.",
    say: "This is labelled a mock — we're not faking a live integration. It shows the contract: pull read-only, push drafts only.",
    click: "Show pull opportunities and push-draft (note 'draft only, never publish').",
    watch: "Honesty about 'mock' builds more trust than a faked live demo." },

  { section: "roi", sel: "#section-roi .section-head",
    title: "14 · ROI — say HOURS BACK, never FTE",
    manual: "Add up all the manual steps you just saw — across the desk, every single day.",
    problem: "That time goes to mechanical work instead of journalism.",
    ai: "The pilot returns it: roughly 3–4 hours back per editor per week.",
    say: "Three to four hours back per editor every week — for reporting and judgment instead of cleanup and reformatting. Same team, more output, more formats.",
    click: "Show the default scenario. Read the per-editor hours, not the aggregate.",
    watch: "NEVER say 'FTE freed' or 'headcount' — to 18 editors that reads as layoffs. Hours-back, always." },

  { section: "operating", sel: "#op-table",
    title: "15 · Operating model + audit",
    manual: "Today there's no single view of who owns what, with what control.",
    problem: "That makes it hard to govern, or to prove accountability.",
    ai: "Every stage has an owner, a KPI and a control, with a full audit trail.",
    say: "This is an operating layer with accountability built in — not a toy.",
    click: "Show the table and the audit log.",
    watch: "Signals you've thought about governance, not just generation." },

  { section: "overview", sel: ".run-demo-bar",
    title: "Close — land on the ask",
    what: "Where to stop and hand it to discussion.",
    say: "You've seen the manual work, the problem with each, and what the system does instead. The ask: a two-to-four-week paid pilot with two or three of your editors and read-only CMS access — measured on acceptance rate and hours saved. Phase 2 builds the moat: true multi-agent, real CMS, Arabic generation, and editorial memory only you will have.",
    click: "Stop here. Hand it to the room.",
    watch: "End on the ask and Phase 2 — not 'what do you think?'." },
];
